# -*- coding: utf-8 -*-
"""[Dicoding Project] ScrappingCode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1_WDueobq5wWyx61rzqxIhK5OjEhZ7Y
"""

!pip install google-play-scraper

# Mengimpor pustaka google_play_scraper untuk mengakses ulasan dan informasi aplikasi dari Google Play Store.
from google_play_scraper import app, reviews_all, Sort

# Mengambil semua ulasan dari aplikasi dengan ID 'com.mobile.legends' di Google Play Store.
# Proses scraping mungkin memerlukan beberapa saat tergantung pada jumlah ulasan yang ada.
scrapreview = reviews_all(
    'com.mobile.legends',  # ID aplikasi
    lang='id',             # Bahasa ulasan (default: 'id')
    country='id',          # Negara (default: 'id')
    sort=Sort.MOST_RELEVANT, # Urutan ulasan (default: Sort.MOST_RELEVANT)          # Jumlah maksimum ulasan yang ingin diambil
)

import csv

with open('mobileLegend_feedback.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review', 'Score'])

    # Menulis konten ulasan dan skornya ke dalam file CSV
    # Asumsi scrapreview[0] adalah list of dictionaries
    for review in scrapreview:
        writer.writerow([review['content'], review['score']])

import csv

# Filter ulasan berdasarkan skor
reviews_high = [review for review in scrapreview if review['score'] >= 4]
reviews_medium = [review for review in scrapreview if review['score'] == 3]
reviews_low = [review for review in scrapreview if review['score'] <= 2]

# Mengambil jumlah ulasan yang diinginkan dari setiap kategori
num_reviews = 4000
selected_reviews = reviews_high[:num_reviews] + reviews_medium[:num_reviews] + reviews_low[:num_reviews]

# Menulis ulasan yang dipilih ke dalam file CSV baru
with open('mobileLegend_feedback_balanced.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review', 'Score'])
    for review in selected_reviews:
        writer.writerow([review['content'], review['score']])

print(f"Successfully created 'mobileLegend_feedback_balanced.csv' with {len(selected_reviews)} reviews.")